export const INDUSTRY_OPTIONS = [
    "Accountant / Bookkeeper",
    "Apprentice (Electrician, Plumber, HVAC)",
    "Barista",
    "Carpenter",
    "Construction",
    "Cook",
    "Cosmetology",
    "Customer Service",
    "Delivery Driver",
    "EMT",
    "Entrepreneur",
    "Facilities Maintenance",
    "Fire Tech",
    "Flooring Installer",
    "Flagger",
    "General Laborer",
    "Groundskeeper / Landscaper",
    "Heavy Equipment Operator",
    "Home Health Aide",
    "Janitor",
    "Logging",
    "Masonry",
    "Medical Assistant",
    "Nursing",
    "Office / Clerical",
    "Painter/Drywaller",
    "Phlebotomist",
    "Restaurant",
    "Retail",
    "Sales Associate",
    "Security Guard",
    "Self-Employed",
    "Warehouse & Logistics",
    "Welder",
    "Other"
].sort();
